### ISSUE TITLE
web server problem

### ISSUE THREAD

**Issue by farsajik** [emelianov/NodeMCU-AJAX-Demo#1]
hi friend.i want to run nodeMCU-AJAX-Demo example wemos d1r1.but it stacks Initializing File system message,thanks

**Comment by emelianov** [comment]
Have you created filesystem and uploaded index.html with 'ESP8266 Sketch Data Upload' Arduino IDE plugin?

**Comment by farsajik** [comment]
yes.i created.another examples from internet works fine with file system.

**Comment by emelianov** [comment]
There is nothing between "Initializing File system..." and next message except filesystem initialization/ So it hangs somewhere inside SPIFFS.begin(). I think something wrong with file system structure or flash chip.
```
    Serial.println("Initializing File system...");
    if (!SPIFFS.begin()) {
        Serial.println("ERROR - File system initialization failed!");
        return;    // init failed
    }
    Serial.println("SUCCESS - File system initialized.");
```
